[2025-06-11T08:38:53.512+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:38:53.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:38:53.517+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:38:53.517+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:38:53.576+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:38:53.575+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:38:53.578+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:38:53.577+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:38:53.579+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:38:53.579+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:38:53.580+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:38:53.580+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:38:53.598+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:38:53.979+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:38:53.979+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:38:53.997+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:38:53.997+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:38:54.027+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.523 seconds
[2025-06-11T08:39:24.320+0000] {processor.py:186} INFO - Started process (PID=128) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:39:24.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:39:24.325+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:24.324+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:39:24.354+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:24.352+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:39:24.355+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:24.355+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:39:24.357+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:24.356+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:39:24.358+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:24.358+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:39:24.361+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:39:24.500+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:24.500+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:39:24.524+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:24.524+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:39:24.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.239 seconds
[2025-06-11T08:39:55.277+0000] {processor.py:186} INFO - Started process (PID=217) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:39:55.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:39:55.281+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:55.281+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:39:55.308+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:55.307+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:39:55.310+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:55.309+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:39:55.311+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:55.311+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:39:55.313+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:55.312+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:39:55.315+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:39:55.352+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:55.351+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:39:55.367+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:39:55.367+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:39:55.391+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.121 seconds
[2025-06-11T08:40:25.596+0000] {processor.py:186} INFO - Started process (PID=282) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:40:25.597+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:40:25.600+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:25.600+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:40:25.628+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:25.627+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:40:25.630+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:25.629+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:40:25.631+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:25.631+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:40:25.632+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:25.632+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:40:25.634+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:40:25.773+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:25.772+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:40:25.790+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:25.790+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:40:25.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.227 seconds
[2025-06-11T08:40:56.053+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:40:56.054+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:40:56.057+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:56.056+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:40:56.084+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:56.083+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:40:56.085+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:56.085+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:40:56.087+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:56.086+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:40:56.088+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:56.088+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:40:56.090+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:40:56.102+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:56.102+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:40:56.120+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:40:56.119+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:40:56.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.100 seconds
[2025-06-11T08:41:26.633+0000] {processor.py:186} INFO - Started process (PID=412) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:41:26.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:41:26.637+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:26.636+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:41:26.660+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:26.659+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:41:26.662+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:26.661+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:41:26.663+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:26.663+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:41:26.664+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:26.664+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:41:26.667+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:41:26.797+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:26.797+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:41:26.812+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:26.812+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:41:26.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.214 seconds
[2025-06-11T08:41:57.292+0000] {processor.py:186} INFO - Started process (PID=477) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:41:57.293+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:41:57.297+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:57.296+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:41:57.323+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:57.322+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:41:57.325+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:57.324+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:41:57.327+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:57.326+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:41:57.329+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:57.328+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:41:57.332+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:41:57.492+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:57.492+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:41:57.520+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:41:57.520+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:41:57.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.261 seconds
[2025-06-11T08:42:27.786+0000] {processor.py:186} INFO - Started process (PID=542) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:42:27.787+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:42:27.789+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:27.789+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:42:27.812+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:27.811+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:42:27.813+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:27.813+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:42:27.815+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:27.814+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:42:27.816+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:27.816+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:42:27.819+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:42:27.852+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:27.851+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:42:27.875+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:27.875+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:42:27.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.122 seconds
[2025-06-11T08:42:58.392+0000] {processor.py:186} INFO - Started process (PID=607) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:42:58.394+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:42:58.399+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:58.399+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:42:58.439+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:58.438+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:42:58.441+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:58.440+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:42:58.442+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:58.442+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:42:58.444+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:58.443+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:42:58.448+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:42:58.657+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:58.656+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:42:58.675+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:42:58.674+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:42:58.706+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.322 seconds
[2025-06-11T08:43:28.903+0000] {processor.py:186} INFO - Started process (PID=672) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:43:28.904+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:43:28.907+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:28.906+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:43:28.928+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:28.927+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:43:28.930+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:28.929+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:43:28.931+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:28.931+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:43:28.932+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:28.932+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:43:28.935+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:43:29.048+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:29.047+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:43:29.073+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:29.073+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:43:29.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.200 seconds
[2025-06-11T08:43:59.758+0000] {processor.py:186} INFO - Started process (PID=737) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:43:59.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:43:59.762+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:59.762+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:43:59.788+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:59.787+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:43:59.790+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:59.789+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:43:59.791+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:59.791+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:43:59.792+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:59.792+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:43:59.795+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:43:59.826+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:59.826+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:43:59.841+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:43:59.841+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:43:59.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.113 seconds
[2025-06-11T08:44:30.871+0000] {processor.py:186} INFO - Started process (PID=802) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:44:30.872+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:44:30.875+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:44:30.874+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:44:30.896+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:44:30.895+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:44:30.897+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:44:30.897+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:44:30.899+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:44:30.898+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:44:30.900+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:44:30.899+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:44:30.902+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:44:31.017+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:44:31.017+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:44:31.030+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:44:31.030+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:44:31.058+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.193 seconds
[2025-06-11T08:45:01.468+0000] {processor.py:186} INFO - Started process (PID=874) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:45:01.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:45:01.472+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:01.472+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:45:01.496+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:01.495+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:45:01.498+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:01.498+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:45:01.500+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:01.500+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:45:01.502+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:01.501+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:45:01.505+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:45:01.539+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:01.539+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:45:01.555+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:01.555+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:45:01.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.117 seconds
[2025-06-11T08:45:31.798+0000] {processor.py:186} INFO - Started process (PID=939) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:45:31.799+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:45:31.802+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:31.801+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:45:31.825+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:31.824+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:45:31.826+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:31.826+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:45:31.828+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:31.827+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:45:31.830+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:31.829+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:45:31.833+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:45:31.972+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:31.971+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:45:31.986+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:45:31.986+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:45:32.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.225 seconds
[2025-06-11T08:46:02.226+0000] {processor.py:186} INFO - Started process (PID=1004) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:46:02.227+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:46:02.229+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:02.229+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:46:02.252+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:02.251+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_product.sql
[2025-06-11T08:46:02.254+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:02.254+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_customer.sql
[2025-06-11T08:46:02.256+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:02.256+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_employee.sql
[2025-06-11T08:46:02.258+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:02.258+0000] {templater.py:94} ERROR - Failed to resolve template field 'sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/dimensions/dim_time.sql
[2025-06-11T08:46:02.262+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:46:02.414+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:02.414+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:46:02.437+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:02.437+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:46:02.462+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.241 seconds
[2025-06-11T08:46:30.475+0000] {processor.py:186} INFO - Started process (PID=1069) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:46:30.476+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:46:30.479+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:30.478+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:46:30.522+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:46:30.535+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:30.534+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:46:30.566+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:46:30.565+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:46:30.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.128 seconds
[2025-06-11T08:47:20.931+0000] {processor.py:186} INFO - Started process (PID=49) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:47:20.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:47:20.936+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:47:20.935+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:47:20.968+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:47:21.108+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:47:21.107+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:47:21.124+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:47:21.124+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:47:21.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.220 seconds
[2025-06-11T08:47:52.167+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:47:52.168+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:47:52.171+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:47:52.170+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:47:52.197+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:47:52.315+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:47:52.315+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:47:52.325+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:47:52.325+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:47:52.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.185 seconds
[2025-06-11T08:48:22.520+0000] {processor.py:186} INFO - Started process (PID=211) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:48:22.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:48:22.525+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:48:22.524+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:48:22.554+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:48:22.681+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:48:22.681+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:48:22.694+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:48:22.693+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:48:22.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.206 seconds
[2025-06-11T08:48:53.252+0000] {processor.py:186} INFO - Started process (PID=276) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:48:53.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:48:53.260+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:48:53.260+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:48:53.332+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:48:53.525+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:48:53.524+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:48:53.538+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:48:53.537+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:48:53.557+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.314 seconds
[2025-06-11T08:49:24.518+0000] {processor.py:186} INFO - Started process (PID=341) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:49:24.519+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:49:24.522+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:49:24.522+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:49:24.552+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:49:24.580+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:49:24.580+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:49:24.594+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:49:24.594+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:49:24.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.107 seconds
[2025-06-11T08:49:55.344+0000] {processor.py:186} INFO - Started process (PID=406) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:49:55.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:49:55.348+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:49:55.348+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:49:55.371+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:49:55.504+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:49:55.503+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:49:55.518+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:49:55.518+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:49:55.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.205 seconds
[2025-06-11T08:50:26.205+0000] {processor.py:186} INFO - Started process (PID=471) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:50:26.206+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:50:26.209+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:50:26.209+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:50:26.240+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:50:26.269+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:50:26.269+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:50:26.283+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:50:26.283+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:50:26.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.110 seconds
[2025-06-11T08:50:56.826+0000] {processor.py:186} INFO - Started process (PID=536) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:50:56.827+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:50:56.832+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:50:56.831+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:50:56.870+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:50:56.991+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:50:56.991+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:50:57.004+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:50:57.003+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:50:57.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.207 seconds
[2025-06-11T08:51:27.597+0000] {processor.py:186} INFO - Started process (PID=601) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:51:27.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:51:27.601+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:51:27.601+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:51:27.630+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:51:27.761+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:51:27.760+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:51:27.784+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:51:27.784+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:51:27.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.217 seconds
[2025-06-11T08:51:58.069+0000] {processor.py:186} INFO - Started process (PID=666) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:51:58.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:51:58.072+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:51:58.072+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:51:58.103+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:51:58.138+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:51:58.137+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:51:58.154+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:51:58.154+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:51:58.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.113 seconds
[2025-06-11T08:52:29.092+0000] {processor.py:186} INFO - Started process (PID=731) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:52:29.093+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:52:29.095+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:52:29.095+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:52:29.119+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:52:29.229+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:52:29.229+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:52:29.240+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:52:29.240+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:52:29.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.172 seconds
[2025-06-11T08:52:59.457+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:52:59.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:52:59.460+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:52:59.460+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:52:59.493+0000] {processor.py:925} INFO - DAG(s) 'data_ingestion_to_stg' retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:52:59.505+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:52:59.505+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2025-06-11T08:52:59.519+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:52:59.519+0000] {dag.py:4156} INFO - Setting next_dagrun for data_ingestion_to_stg to None, run_after=None
[2025-06-11T08:52:59.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.092 seconds
[2025-06-11T08:53:30.421+0000] {processor.py:186} INFO - Started process (PID=861) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:53:30.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:53:30.425+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:53:30.424+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:53:30.451+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:53:30.447+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/sql/data_ingestion_to_stg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sql/data_ingestion_to_stg.py", line 11, in <module>
    import files.func_python as func
ModuleNotFoundError: No module named 'files.func_python'
[2025-06-11T08:53:30.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:53:30.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.058 seconds
[2025-06-11T08:54:00.808+0000] {processor.py:186} INFO - Started process (PID=926) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:54:00.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:54:00.811+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:54:00.811+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:54:00.830+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:54:00.827+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/sql/data_ingestion_to_stg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sql/data_ingestion_to_stg.py", line 11, in <module>
    import files.func_python as func
ModuleNotFoundError: No module named 'files.func_python'
[2025-06-11T08:54:00.831+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:54:00.849+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.046 seconds
[2025-06-11T08:54:31.225+0000] {processor.py:186} INFO - Started process (PID=991) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:54:31.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:54:31.227+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:54:31.227+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:54:31.246+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:54:31.243+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/sql/data_ingestion_to_stg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sql/data_ingestion_to_stg.py", line 11, in <module>
    import files.func_python as func
ModuleNotFoundError: No module named 'files.func_python'
[2025-06-11T08:54:31.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:54:31.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.044 seconds
[2025-06-11T08:55:01.417+0000] {processor.py:186} INFO - Started process (PID=1056) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:55:01.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:55:01.419+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:55:01.419+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:55:01.445+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:55:01.441+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/sql/data_ingestion_to_stg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sql/data_ingestion_to_stg.py", line 11, in <module>
    import files.func_python as func
ModuleNotFoundError: No module named 'files.func_python'
[2025-06-11T08:55:01.446+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:55:01.465+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.054 seconds
[2025-06-11T08:55:32.493+0000] {processor.py:186} INFO - Started process (PID=1121) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:55:32.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:55:32.495+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:55:32.495+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:55:32.520+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:55:32.516+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/sql/data_ingestion_to_stg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sql/data_ingestion_to_stg.py", line 11, in <module>
    import files.func_python as func
ModuleNotFoundError: No module named 'files.func_python'
[2025-06-11T08:55:32.522+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:55:32.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.054 seconds
[2025-06-11T08:56:02.710+0000] {processor.py:186} INFO - Started process (PID=1186) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:56:02.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:56:02.713+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:56:02.712+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:56:02.730+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:56:02.727+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/sql/data_ingestion_to_stg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sql/data_ingestion_to_stg.py", line 11, in <module>
    import files.func_python as func
ModuleNotFoundError: No module named 'files.func_python'
[2025-06-11T08:56:02.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:56:02.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.044 seconds
[2025-06-11T08:56:33.497+0000] {processor.py:186} INFO - Started process (PID=1251) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:56:33.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:56:33.500+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:56:33.500+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:56:33.538+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:56:33.533+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/sql/data_ingestion_to_stg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sql/data_ingestion_to_stg.py", line 11, in <module>
    import files.func_python as func
ModuleNotFoundError: No module named 'files.func_python'
[2025-06-11T08:56:33.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:56:33.569+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.080 seconds
[2025-06-11T08:57:04.411+0000] {processor.py:186} INFO - Started process (PID=1316) to work on /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:57:04.455+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/sql/data_ingestion_to_stg.py for tasks to queue
[2025-06-11T08:57:04.456+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:57:04.456+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:57:04.497+0000] {logging_mixin.py:190} INFO - [2025-06-11T08:57:04.492+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/sql/data_ingestion_to_stg.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/sql/data_ingestion_to_stg.py", line 11, in <module>
    import files.func_python as func
ModuleNotFoundError: No module named 'files.func_python'
[2025-06-11T08:57:04.498+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/sql/data_ingestion_to_stg.py
[2025-06-11T08:57:04.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/sql/data_ingestion_to_stg.py took 0.120 seconds
